**Speed Comparsion Between List And Numpy**

In [1]:
import numpy as np
import time

In [2]:
a=[1,2,3,4,5,6,7,8,9,10] * 1000000  #List

start=time.time()
for i in range(len(a)):
  a[i]=a[i]*2

print("\nTime taken for list",time.time()-start)



Time taken for list 1.858064889907837


In [3]:
a=[1,2,3,4,5,6,7,8,9,10] * 1000000   #Numpy
b=np.array(a)
start=time.time()
nedw_b=b*2
print("\nTime taken for numpy array",time.time()-start)


Time taken for numpy array 0.0986642837524414


**Memory Comparsion Between List And Array**

In [4]:
import sys

In [5]:
a=[1,2,3,4,5]
arr=np.array(a)
print("List size:",sys.getsizeof(a))
print("ArraySize:",arr.nbytes)

List size: 104
ArraySize: 40


**DataType** **Checking**

In [6]:
a=[1,'a',"apple",2.1]
print(type(a))

<class 'list'>


In [7]:
arr=np.array(a)
arr

array(['1', 'a', 'apple', '2.1'], dtype='<U32')

**Numpy Example **

In [8]:


import numpy as np

In [9]:
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [10]:

#Dimensions and shape of an array
arr.ndim

1

In [11]:
arr=np.array(34) # Scalar Value is 0
arr.ndim

0

In [12]:
a=np.array([[[[]]]])
a.ndim

4

In [13]:
a.shape

(1, 1, 1, 0)

**Numpy Main Example**

In [14]:
import numpy as np
range=np.arange(1,10,2)  #start,stop,step
range

array([1, 3, 5, 7, 9])

In [15]:
arr=np.linspace(0,1,10)  #start,stop,Number_of_values_between_Them
arr

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [16]:
arr=np.logspace(1,3,3) #logarithmic scale array --> 10^1 --->10^3 ...3 points
arr

array([  10.,  100., 1000.])

In [17]:
#np.zeros -> array full of zeros
arr=np.zeros(5)
arr

array([0., 0., 0., 0., 0.])

In [18]:
arr=np.zeros([2,3]) #2 Rows,3 Columns
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [19]:
#np.ones -> array full of ones
arr=np.ones([4,2])
arr

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [20]:
arr=np.full(10,2) #-->create an array full of any value
arr

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [21]:
arr=np.full([2,4],7) #[row,column],default value
arr

array([[7, 7, 7, 7],
       [7, 7, 7, 7]])

In [22]:
arr=np.empty([2,3]) #Unintialized array -->Create an array without setting any value
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [23]:
arr=np.random.rand(10) # --> random floats(0 to 1)
arr

array([0.5824252 , 0.9375257 , 0.95253545, 0.91502662, 0.57652139,
       0.11330717, 0.8416258 , 0.52447089, 0.6949513 , 0.49047821])

In [24]:
arr=np.random.rand(2,3)
arr

array([[0.56403228, 0.51279615, 0.49503133],
       [0.02206152, 0.18681987, 0.56394936]])

In [25]:
arr=np.random.randn(2,3) # --> random floats from standard normal distribution
arr

array([[-0.07064086, -1.01949152, -0.46285696],
       [ 2.04512642, -0.45172963, -0.68673051]])

In [26]:
arr=np.random.randint(10,100,size=(2,3))   #--> start,stop,dimension/number  # random integers
arr

array([[46, 80, 43],
       [62, 94, 51]])

**Numpy Data Types and Type Casting**

In [27]:
arr=np.array([1,2,3.1,4,5])
arr

array([1. , 2. , 3.1, 4. , 5. ])

In [28]:
print(type(arr))

<class 'numpy.ndarray'>


In [29]:
lst=["String",1,2,5.6]
arr=np.array(lst)
arr

array(['String', '1', '2', '5.6'], dtype='<U32')

In [30]:
arr=np.array([1,2,31,4,5])
arr

array([ 1,  2, 31,  4,  5])

In [31]:
arr.dtype

dtype('int64')

In [32]:
arr=np.array([1,2.1,3,4],dtype=np.float64)

In [33]:
arr.dtype

dtype('float64')

In [34]:
#type casting ->astype()
arr=np.array([1,2,3])
arr.dtype

dtype('int64')

In [35]:
new_arr=arr.astype(np.float64)
new_arr

array([1., 2., 3.])

In [36]:
new_arr.dtype

dtype('float64')

In [37]:
new_arr2=new_arr.astype(np.int64)
new_arr2

array([1, 2, 3])

In [38]:
# Type Casting Errors:
arr=np.array(["1","2","hello"])   #We can't convert string into a integer,float
arr2=arr.astype(np.int64)
arr2

ValueError: invalid literal for int() with base 10: np.str_('hello')

In [41]:
arr=np.array([[1,2,3],[4,5,6]])
arr

dtype('int64')

In [42]:
arr.dtype

dtype('int64')

In [43]:
arr.ndim

2

In [44]:
arr.shape

(2, 3)

In [45]:
arr.size

6

In [46]:
arr.itemsize  # Each Element Takes 8 Bytes of Memory

8

**Array Reshaping ->Reshape,Ravel,Flatten**

In [52]:
arr=np.array([1,2,3,4,5,6])
reshaped=arr.reshape(2,3)
print(reshaped)

[[1 2 3]
 [4 5 6]]


In [53]:
reshape2=reshaped.reshape(3,2)
reshape2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [54]:
#ravel -> convert 1D Array
ravel = reshape2.ravel()
ravel

array([1, 2, 3, 4, 5, 6])

In [55]:
ravel[0]=100
print(ravel)
print(reshape2)

[100   2   3   4   5   6]
[[100   2]
 [  3   4]
 [  5   6]]


In [56]:
#faltten -> to 1D Array
# -> returns a copy of the array

flat=reshape2.flatten()
flat

array([100,   2,   3,   4,   5,   6])

In [58]:
flat[0]=1

In [59]:
flat

array([1, 2, 3, 4, 5, 6])

In [60]:
reshape2

array([[100,   2],
       [  3,   4],
       [  5,   6]])

**Arithmetic Operations On Arrays**

In [61]:
a=np.array([1,2,3])
b=np.array([4,5,6])

In [67]:
#Addition:
print(a+b)

[5 7 9]


In [68]:
#Subtraction
print(a-b)

[-3 -3 -3]


In [69]:
print(b-a)

[3 3 3]


In [70]:
#Division
print(a/b)

[0.25 0.4  0.5 ]


In [66]:
#Multiplication
print(a*b)

[ 4 10 18]


In [72]:
#modules -> Remainder
print(b%a)

[0 1 0]


In [73]:
#exponent -> power
print(a**2)

[1 4 9]


**Universal Functions -> ufuncs**

In [78]:
arr=np.array([1,4,9,16,35,72])

In [79]:
# Square root -> np.sqrt()
print(np.sqrt(arr))

[1.         2.         3.         4.         5.91607978 8.48528137]


In [80]:
#exponential -> np.exp --> e^x -> x is any Integer

print(np.exp([1,2]))

[2.71828183 7.3890561 ]


In [81]:
#sine function -> np.sin

angles=np.array([0,np.pi,np.pi/2])
print(np.sin(angles))

[0.0000000e+00 1.2246468e-16 1.0000000e+00]


**Indexing And Slicing**

In [82]:
a=[1,2,3,4,5]

In [85]:
a[-1:-4:-1]

[5, 4, 3]

In [87]:
a[: :2]

[1, 3, 5]

In [97]:
arr=np.array([10,20,30,40,50])
arr[::2]

array([10, 30, 50])

In [99]:
# Negative Indexing
print(arr[-1])

50


In [101]:
matrix=np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

In [103]:
print(matrix[0:2,:])

[[1 2 3]
 [4 5 6]]


In [104]:
print(matrix[0:2,0:3])

[[1 2 3]
 [4 5 6]]


In [105]:
print(matrix[1:,1:])

[[5 6]
 [8 9]]


In [106]:
#np.take --> built in function to perform indexing and slicing
arr=np.array([10,20,30,40,50])
ind=[0,2]
print(np.take(arr,ind))

[10 30]


In [107]:
# Itearting with nditer()

In [109]:
arr=np.array([[1,2],[3,4]])


In [110]:
for x in np.nditer(arr):
  print(x,end=" ")

1 2 3 4 

In [111]:
# ndenumerate() --> both index + value
for ind,x in np.ndenumerate(arr):
  print(ind,x)

(0, 0) 1
(0, 1) 2
(1, 0) 3
(1, 1) 4


In [112]:
# Views Vs Copies
arr=np.array([1,2,3,4,5])
view=arr[1:3]
view

array([2, 3])

In [113]:
view[0]=200

In [114]:
view

array([200,   3])

In [115]:
arr

array([  1, 200,   3,   4,   5])

In [117]:
# Copy
copy=arr[1:3].copy()
copy

array([200,   3])

In [118]:
copy[0]=2
copy

array([2, 3])

In [119]:
arr

array([  1, 200,   3,   4,   5])

In [123]:
arr=np.array([[1,2],[3,4]])
arr

array([[1, 2],
       [3, 4]])

In [125]:
print(arr.transpose())

[[1 3]
 [2 4]]


In [129]:
# Swapaxes --> swap 2 specific axes in a matrix.
arr=np.array([[[1,2],[3,4]]])
arr.shape

(1, 2, 2)

In [131]:
swap=np.swapaxes(arr,0,1)
swap.shape

(2, 1, 2)

In [132]:
# Concatenation:
a=np.array([1,2])
b=np.array([3,4])

In [134]:
combine=np.concatenate((a,b))
combine

array([1, 2, 3, 4])

In [136]:
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])

In [141]:
print(np.vstack((arr1,arr2)))    # vertical Stack

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [142]:
print(np.hstack((arr1,arr2)))    # Horizontal Stack

[[1 2 5 6]
 [3 4 7 8]]


In [144]:
print(np.stack((arr1,arr2),axis=0))

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [145]:
#Splitting Arrays
arr1=np.array([[1,2],[3,4],[5,6],[7,8]])

In [146]:
arr1

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [149]:
print(np.split(arr1,2))

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]


In [150]:
print(np.split(arr1,4))

[array([[1, 2]]), array([[3, 4]]), array([[5, 6]]), array([[7, 8]])]


In [151]:
print(np.vsplit(arr1,2))

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]


In [152]:
print(np.hsplit(arr1,2))

[array([[1],
       [3],
       [5],
       [7]]), array([[2],
       [4],
       [6],
       [8]])]


In [154]:
# Repeating :
arr=np.array([1,2,3])
print(np.repeat(arr,3))

[1 1 1 2 2 2 3 3 3]


In [155]:
# tile --> repeat my whole array
print(np.tile(arr,2))

[1 2 3 1 2 3]


In [156]:
# Aggregate Functions:
arr=np.array([1,2,3])
print(np.sum(arr))

6


In [157]:
np.mean(arr)

np.float64(2.0)

In [158]:
np.median(arr)

np.float64(2.0)

In [159]:
np.std(arr)

np.float64(0.816496580927726)

In [160]:
np.var(arr)

np.float64(0.6666666666666666)

In [161]:
np.min(arr)

np.int64(1)

In [162]:
np.max((arr))

np.int64(3)

In [163]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [166]:
print(np.sum(matrix,axis=0))

[12 15 18]


In [167]:
# Cumulative Operations --> running total
arr

array([1, 2, 3])

In [168]:
print(np.cumsum(arr))

[1 3 6]


In [170]:
print(np.cumprod(arr))

[1 2 6]


**Conditional Based Choices**

In [171]:
# Where:
arr

array([1, 2, 3])

In [172]:
result=np.where(arr<2,"low","High")
result

array(['low', 'High', 'High'], dtype='<U4')

In [173]:
#argwhere : row-column positions for 2d arrays

In [174]:
arr

array([1, 2, 3])

In [180]:
arr=np.array([90,19,35,50])
arr

array([90, 19, 35, 50])

In [181]:
print(np.argwhere(arr>20))

[[0]
 [2]
 [3]]


In [182]:
mask=np.logical_and(arr>15,arr<35)

In [184]:
mask

array([False,  True, False, False])

In [185]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [186]:
print(np.argwhere(matrix>5))

[[1 2]
 [2 0]
 [2 1]
 [2 2]]


In [187]:
# Logical And:
arr

array([90, 19, 35, 50])

In [189]:
mask=np.logical_and(arr>30,arr<51)

In [190]:
mask

array([False, False,  True,  True])

In [191]:
#Logical or;
mask=np.logical_or(arr>30,arr<51)

In [192]:
mask

array([ True,  True,  True,  True])

In [193]:
# Broadcating

In [194]:
image=np.array([[200,150],[100,250]])
image

array([[200, 150],
       [100, 250]])

In [196]:
brightness=image+50
brightness

array([[250, 200],
       [150, 300]])

In [197]:
#Vectorization:
#np.vectorize() --> Convert a regular function to be applied on an array

In [198]:
def square(x):
  return x*x

vfunc=np.vectorize(square)

In [199]:
arr

array([90, 19, 35, 50])

In [200]:
print(vfunc(arr))

[8100  361 1225 2500]


In [201]:
# Dealing with Missing Values
# np.nan --> not a number


In [202]:
a=np.array([1,2,np.nan,4])

In [203]:
a

array([ 1.,  2., nan,  4.])

In [204]:
# np.inf and -np.inf -->positive and negative infinite VALUES

In [205]:
#np.isnan
#np.isinf
#np.isfinite

#--> These are the functions used to detect any null values,infinite value or finite values

In [206]:
print(np.isnan(a))

[False False  True False]


In [207]:
b=np.array([1,np.nan,np.inf,10.2,40])

In [208]:
print(np.isinf(b))

[False False  True False False]


In [209]:
new_b=np.nan_to_num(b) #remove Nan / infinite Values.

In [210]:
new_b

array([1.00000000e+000, 0.00000000e+000, 1.79769313e+308, 1.02000000e+001,
       4.00000000e+001])